version: '3'
services:
    
    # PHP Service
    app:
        build: ./config/php
        container_name: CORE_PHP
        restart: unless-stopped
        tty: true
        env_file:
            - ".env"
        networks:
            - app-network
        volumes:
            - "./www:/var/www"
            - "./config/php/app.crontab:/etc/cron.d/app.crontab"
            - "./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini"
        command: [ "/bin/bash", "/usr/local/bin/start" ]
    webserver:
        image: nginx:alpine
        container_name: CORE_NGINX
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
        volumes:
            - "/etc/ssl:/etc/ssl"
            - "/var/log/nginx:/var/log/nginx"
            - "./www:/var/www"
            - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./config/nginx/conf.d/:/etc/nginx/conf.d/:ro"

    #PostgreSql Service

    pgsql:
        image: postgres:latest
        container_name: CORE_PSQL
        restart: unless-stopped
        tty: true
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: root
        networks:
            - app-network
        volumes:
            - dbdata:/var/lib/pgsql
            - "./config/pgsql/pg_conf.cnf:/etc/pgsql/pg_conf.cnf"

#Docker Networks
networks:
  app-network:
    driver: bridge

#Docker Volumes
volumes:
  dbdata:
    driver: local
